# Generated by Django 2.2.13 on 2020-08-27 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200827_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(choices=[('EDU', 'Education')], default='EDU', max_length=3),
        ),
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 16, 56, 59, 993635, tzinfo=utc)),
        ),
    ]
