# Generated by Django 2.2.13 on 2020-08-27 17:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200827_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 17, 20, 11, 27451, tzinfo=utc)),
        ),
    ]
