# Generated by Django 2.2.13 on 2020-08-28 16:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200827_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 28, 16, 28, 0, 824227, tzinfo=utc)),
        ),
    ]
