# Generated by Django 2.2.13 on 2020-08-29 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200829_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='datetime',
        ),
        migrations.AlterField(
            model_name='cv',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 29, 19, 19, 19, 92488, tzinfo=utc)),
        ),
    ]
