# Generated by Django 2.2.13 on 2020-08-30 11:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200829_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2020, 8, 30, 11, 29, 43, 328222, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cv',
            name='tag',
            field=models.CharField(choices=[('Achievements', 'Achievements'), ('Education', 'Education'), ('Work Experience', 'Work Experience')], default='Education', max_length=200),
        ),
    ]
